[deps]
BiologicalScaling = "726553fe-cdfb-47ef-9d36-6d238d32ce3c"
BiophysicalGeometry = "06c61620-4f66-4020-a018-07befe374221"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
FluidProperties = "d16f1b92-71d3-42f3-aafa-43e5bb0efda8"
HeatExchange = "720bd838-cdd6-4aad-926b-452b962dce21"
Microclimate = "fa5d2a79-de00-40ba-a9f4-ff140fbe07ba"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SolarRadiation = "d01e3663-6acb-4162-92ee-c50acb918cac"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
ThermalPhysiology = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[sources]
BiologicalScaling = {rev = "main", url = "https://github.com/BiophysicalEcology/BiologicalScaling.jl"}
BiophysicalGeometry = {rev = "main", url = "https://github.com/BiophysicalEcology/BiophysicalGeometry.jl"}
FluidProperties = {rev = "main", url = "https://github.com/BiophysicalEcology/FluidProperties.jl"}
HeatExchange = {rev = "transient-model", url = "https://github.com/BiophysicalEcology/HeatExchange.jl"}
Microclimate = {rev = "Docs", url = "https://github.com/BiophysicalEcology/Microclimate.jl"}
SolarRadiation = {rev = "main", url = "https://github.com/BiophysicalEcology/SolarRadiation.jl"}
ThermalPhysiology = {path = ".."}

[compat]
Documenter = "1"
